---
version: 2.1

jobs:
  build:
    docker:
    - image: circleci/golang:1.16
      environment:
        CYPRESS_VERSION: 7.2.0

    steps:
    # pull sources
    - checkout

    - restore_cache:
        keys:
        - cypress-parallel-cli-{{ checksum "go.mod" }}

    - run:
        name: Install nodejs and cypress
        command: |
          which node || curl -fsSL https://deb.nodesource.com/setup_14.x | sudo -E bash -
          which node || sudo apt update
          which node || sudo apt-get install -y nodejs

          which cypress &> /dev/null || sudo apt install libgconf-2-4 libatk1.0-0 libatk-bridge2.0-0 libgdk-pixbuf2.0-0 libgtk-3-0 libgbm-dev libnss3-dev libxss-dev libasound2
          which cypress &> /dev/null || npm install -g cypress@${CYPRESS_VERSION} --unsafe-perm --silent
          cypress verify
    
    - run:
        name: download mage
        command: go get -u github.com/magefile/mage

    - run:
        name: Install golang dependencies
        command: mage installDeps
    
    - save_cache:
        key: cypress-parallel-cli-{{ checksum "go.mod" }}
        paths:
        - /go/pkg/mod
        - ~/.npm-global/

    - run:
        name: Perform unit testing
        no_output_timeout: 30m
        command: go test -v ./... -coverprofile=coverage.out

    - run:
        name: Print result of unit testing
        command: go tool cover -func=coverage.out

    - run:
        name: Generate binaries
        command: mage build

    - run:
        name: Compress binaries
        command: mage compress

    - run:
        name: Cleaning binaries
        command: mage clean

workflows:
  version: 2
  test-and-build:
    jobs:
    - build