---
version: 2.1

# https://circleci.com/developer/images/image/cimg/go

executors:
  golang:
    docker:
    - image: cimg/go:1.16-node

jobs:
  build:
    executor: golang
    environment:
      BUILD_VERSION: "v${CIRCLE_TAG}"
      BUILD_REVISION: $(git rev-list -1 HEAD)

    steps:
    # pull sources
    - checkout

    - restore_cache:
        keys:
        - cypress-parallel-cli-{{ checksum "go.mod" }}-1

    - run:
        name: download mage
        command: go get -u github.com/magefile/mage

    - run:
        name: Install golang dependencies
        command: mage installDeps

    - run:
        name: Generate binaries
        command: |
          pwd
          mage build
          ls -lrta $PWD
          sudo find / -path /proc -prune -false -o -name "cypress-parallel-cli_*"

    - run:
        name: Compress binaries
        command: mage compress

  build-tags-and-publish-prerelease:
    executor: golang
    environment:
      BUILD_VERSION: "v${CIRCLE_TAG}"
      BUILD_REVISION: $(git rev-list -1 HEAD)

    steps:
    # pull sources
    - checkout

    - restore_cache:
        keys:
        - cypress-parallel-cli-{{ checksum "go.mod" }}-1

    - run:
        name: download mage
        command: go get -u github.com/magefile/mage

    - run:
        name: Install golang dependencies
        command: mage installDeps

    - run:
        name: Generate binaries
        command: mage build

    - run:
        name: Compress binaries
        command: mage compress

    - run:
        name: Publish prerelease
        command: |
          go get github.com/tcnksm/ghr
          git checkout .
          ghr -t ${GITHUB_ACCESS_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_BRANCH} -n ${CIRCLE_TAG} -prerelease ${BUILD_VERSION} artifacts/

    - run:
        name: Cleaning binaries
        command: mage clean

  build-tags-and-publish-release:
    executor: golang
    environment:
      BUILD_VERSION: "v${CIRCLE_TAG}"
      BUILD_REVISION: $(git rev-list -1 HEAD)

    steps:
    # pull sources
    - checkout

    - restore_cache:
        keys:
        - cypress-parallel-cli-{{ checksum "go.mod" }}-1

    - run:
        name: download mage
        command: go get -u github.com/magefile/mage

    - run:
        name: Install golang dependencies
        command: mage installDeps

    - run:
        name: Generate binaries
        command: mage build

    - run:
        name: Compress binaries
        command: mage compress

    - run:
        name: Publish release
        command: |
          go get github.com/tcnksm/ghr
          git checkout .
          ghr -t ${GITHUB_ACCESS_TOKEN} -u ${CIRCLE_PROJECT_USERNAME} -r ${CIRCLE_PROJECT_REPONAME} -c ${CIRCLE_BRANCH} -n ${CIRCLE_TAG} ${BUILD_VERSION} artifacts/

    - run:
        name: Cleaning binaries
        command: mage clean

# https://circleci.com/docs/2.0/workflows/#git-tag-job-execution
workflows:
  version: 2
  test-and-build:
    jobs:
    - build:
        filters:
          tags:
            only: /.*/
    - build-tags-and-publish-prerelease:
        requires:
        - build
        filters:
          tags:
            only: /^\d+\.\d+\.\d+-(.*)$/
          branches:
            ignore: /.*/
    - build-tags-and-publish-release:
        requires:
        - build
        filters:
          tags:
            only: /^\d+\.\d+\.\d+$/
          branches:
            ignore: /.*/
